force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <description>System Alerts to notify users of issues on records in Salesforce.</description>
    <label>Alert</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Alert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alert__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
                <default>true</default>
                <label>Info</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Danger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactAlert__c/ContactAlert__c.object-meta.xml
<CustomObject>
    <description>Associate Contacts with Alerts</description>
    <label>Contact Alert</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>Contact Alert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactAlert__c/fields/Alert__c.field-meta.xml
<CustomField>
    <fullName>Alert__c</fullName>
    <label>Alert</label>
    <referenceTo>Alert__c</referenceTo>
    <relationshipLabel>Contact Alerts</relationshipLabel>
    <relationshipName>ContactAlerts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactAlert__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Alerts</relationshipLabel>
    <relationshipName>ContactAlerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContactAlertPanelAuraServiceTest.cls
@isTest
private class ContactAlertPanelAuraServiceTest {
  @TestSetup
  static void setupData() {
    Contact con = new Contact(LastName = 'Test');
    insert con;
    Alert__c alert = new Alert__c(
      Name = 'Test Alert',
      Type__c = 'Danger',
      Description__c = 'So dangerous.'
    );
    insert alert;

    ContactAlert__c ca = new ContactAlert__c(
      Contact__c = con.Id,
      Alert__c = alert.Id
    );
    insert ca;
  }

  static testMethod void getAlertsByAccount_givenAccountId_shouldGetAlerts() {
    Contact con = [SELECT Id FROM Contact LIMIT 1];

    Test.startTest();

    List<AlertModel> alerts = ContactAlertPanelAuraService.getAlertsByContact(
      con.Id
    );

    Test.stopTest();

    System.assert(!alerts.isEmpty());
  }
}