force-app/main/default/objects/AccountAlert__c/AccountAlert__c.object-meta.xml
<CustomObject>
    <description>Associate Accounts to Alerts</description>
    <label>Account Alert</label>
    <nameField>
        <displayFormat>AA-{00000000}</displayFormat>
        <label>Account Alert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAlert__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Alerts</relationshipLabel>
    <relationshipName>Account_Alerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAlert__c/fields/Alert__c.field-meta.xml
<CustomField>
    <fullName>Alert__c</fullName>
    <label>Alert</label>
    <referenceTo>Alert__c</referenceTo>
    <relationshipLabel>Account Alerts</relationshipLabel>
    <relationshipName>Account_Alerts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <description>System Alerts to notify users of issues on records in Salesforce.</description>
    <label>Alert</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Alert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alert__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
                <default>true</default>
                <label>Info</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Danger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/test/default/classes/auraServices/AccountAlertPanelAuraServiceTest.cls
@isTest
private class AccountAlertPanelAuraServiceTest {
  @TestSetup
  static void setupData() {
    Account acc = new Account(Name = 'Test Account');
    insert acc;
    Alert__c alert = new Alert__c(
      Name = 'Test Alert',
      Type__c = 'Danger',
      Description__c = 'So dangerous.'
    );
    insert alert;

    AccountAlert__c aa = new AccountAlert__c(
      Account__c = acc.Id,
      Alert__c = alert.Id
    );
    insert aa;
  }

  @isTest
  static void getAlertsByAccount_givenAccountId_shouldGetAlerts() {
    Account acc = [SELECT Id FROM Account LIMIT 1];

    Test.startTest();

    List<AlertModel> alerts = AccountAlertPanelAuraService.getAlertsByAccount(
      acc.Id
    );

    Test.stopTest();

    System.assert(!alerts.isEmpty());
  }
}