force-app/main/default/objects/AccountAlert__c/AccountAlert__c.object-meta.xml
<CustomObject>
    <description>Associate Accounts to Alerts</description>
    <label>Account Alert</label>
    <nameField>
        <displayFormat>AA-{00000000}</displayFormat>
        <label>Account Alert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAlert__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Alerts</relationshipLabel>
    <relationshipName>Account_Alerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAlert__c/fields/Alert__c.field-meta.xml
<CustomField>
    <fullName>Alert__c</fullName>
    <label>Alert</label>
    <referenceTo>Alert__c</referenceTo>
    <relationshipLabel>Account Alerts</relationshipLabel>
    <relationshipName>Account_Alerts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAlert__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description
  >Contextual info message pertaining to the Account for which the Alert is associated.</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <description>System Alerts to notify users of issues on records in Salesforce.</description>
    <label>Alert</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Alert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alert__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <formula>IF(TEXT(Type__c) = &#39;Danger&#39;, 3,
  IF(TEXT(Type__c) = &#39;Warning&#39;, 2,
    IF(TEXT(Type__c) = &#39;Info&#39;, 1, 0)
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
                <default>true</default>
                <label>Info</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Danger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountAlertsPanelAuraService.cls
public with sharing class AccountAlertsPanelAuraService {

	@AuraEnabled
	public static List<AlertModel> getAlertsByAccount(Id accountId) {
		List<AccountAlert__c> accountAlerts = [
			SELECT Id,
				Message__c,
				Alert__r.Type__c,
				Alert__r.Name,
				Alert__r.Description__c,
				Alert__r.Rank__c
			FROM AccountAlert__c
			WHERE Account__c = :accountId
				AND IsActive__c = true];

		List<AlertModel> alerts = new List<AlertModel>();
		for (AccountAlert__c aa : accountAlerts) {
			alerts.add(new AlertModel(aa));
		}
		return alerts;
	}

	public class AlertModel {
		@AuraEnabled
		public Id id {get; private set;}
		@AuraEnabled
		public String title {get; private set;}
		@AuraEnabled
		public String description {get; private set;}
		@AuraEnabled
		public String message {get; private set;}
		@AuraEnabled
		public String type {get; private set;}
		@AuraEnabled
		public Integer rank {get; private set;}

		public AlertModel(AccountAlert__c aa) {
			id = aa.Id;
			title = aa.Alert__r.Name;
			description = aa.Alert__r.Description__c;
			message = aa.Message__c;
			type = aa.Alert__r.Type__c;
			rank = Integer.valueOf(aa.Alert__r.Rank__c);
		}
	}
}