force-app/main/default/objects/AccountAlert__c/AccountAlert__c.object-meta.xml
<CustomObject>
    <description>Associate Accounts to Alerts</description>
    <label>Account Alert</label>
    <nameField>
        <displayFormat>AA-{00000000}</displayFormat>
        <label>Account Alert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAlert__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Alerts</relationshipLabel>
    <relationshipName>Account_Alerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAlert__c/fields/Alert__c.field-meta.xml
<CustomField>
    <fullName>Alert__c</fullName>
    <label>Alert</label>
    <referenceTo>Alert__c</referenceTo>
    <relationshipLabel>Account Alerts</relationshipLabel>
    <relationshipName>Account_Alerts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAlert__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description
  >Contextual info message pertaining to the Account for which the Alert is associated.</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__c/Alert__c.object-meta.xml
<CustomObject>
    <description>System Alerts to notify users of issues on records in Salesforce.</description>
    <label>Alert</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Alert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alert__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <formula>IF(TEXT(Type__c) = &#39;Danger&#39;, 3,
  IF(TEXT(Type__c) = &#39;Warning&#39;, 2,
    IF(TEXT(Type__c) = &#39;Info&#39;, 1, 0)
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Alert__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
                <default>true</default>
                <label>Info</label>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Danger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContactAlert__c/ContactAlert__c.object-meta.xml
<CustomObject>
    <description>Associate Contacts with Alerts</description>
    <label>Contact Alert</label>
    <nameField>
        <displayFormat>CA-{00000000}</displayFormat>
        <label>Contact Alert Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ContactAlert__c/fields/Alert__c.field-meta.xml
<CustomField>
    <fullName>Alert__c</fullName>
    <label>Alert</label>
    <referenceTo>Alert__c</referenceTo>
    <relationshipLabel>Contact Alerts</relationshipLabel>
    <relationshipName>ContactAlerts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactAlert__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Alerts</relationshipLabel>
    <relationshipName>ContactAlerts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ContactAlert__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description
  >Contextual info message pertaining to the Contact for which the Alert is associated.</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AlertModelTest.cls
@isTest
private class AlertModelTest {

	@TestSetup
	static void setupData() {
		Account acc = new Account(Name = 'Test Account');
		insert acc;
		Contact con = new Contact(
			LastName = 'Test',
			AccountId = acc.Id);
		insert con;
		Alert__c alert = new Alert__c(
			Name = 'Test Alert',
			Type__c = 'Danger',
			Description__c = 'So dangerous.');
		insert alert;

		AccountAlert__c aa = new AccountAlert__c(
			Account__c = acc.Id,
			Alert__c = alert.Id);
		insert aa;

		ContactAlert__c ca = new ContactAlert__c(
			Contact__c = con.Id,
			Alert__c = alert.Id);
		insert ca;
	}

	static TestMethod void constructor_givenAccountAlert_shouldGetAlertModel() {
		AccountAlert__c aa = [
			SELECT Id,
				Alert__c,
				Alert__r.Name,
				Alert__r.Description__c,
				Alert__r.Type__c,
				Alert__r.Rank__c,
				Message__c
			FROM AccountAlert__c
			LIMIT 1];

		Test.startTest();

			AlertModel alert = new AlertModel(aa);

		Test.stopTest();

		System.assertNotEquals(null, alert);
	}

	static TestMethod void constructor_givenContactAlert_shouldGetAlertModel() {
		ContactAlert__c ca = [
			SELECT Id,
				Alert__c,
				Alert__r.Name,
				Alert__r.Description__c,
				Alert__r.Type__c,
				Alert__r.Rank__c,
				Message__c
			FROM ContactAlert__c
			LIMIT 1];

		Test.startTest();

			AlertModel alert = new AlertModel(ca);

		Test.stopTest();

		System.assertNotEquals(null, alert);
	}
}